export const mockDistricts = [
  { name: '长宁区', slug: 'changning-qu', count: 42 },
  { name: '静安区', slug: 'jingan-qu', count: 38 },
  { name: '徐汇区', slug: 'xuhui-qu', count: 45 },
  { name: '浦东新区', slug: 'pudong-xinqu', count: 56 },
  { name: '虹口区', slug: 'hongkou-qu', count: 31 },
  { name: '杨浦区', slug: 'yangpu-qu', count: 28 },
  { name: '黄浦区', slug: 'huangpu-qu', count: 25 },
  { name: '普陀区', slug: 'putuo-qu', count: 22 },
];

export const mockServiceTypes = [
  { name: '居家护理', slug: 'hugong', description: '全天/半天居家照护、生活起居、康复训练', count: 156 },
  { name: '陪诊服务', slug: 'peizhen', description: '医院陪诊、代取药、检查陪同', count: 89 },
  { name: '日间照料', slug: 'rijian-zhaoliao', description: '日托服务、社区养老驿站', count: 67 },
  { name: '术后康复', slug: 'shuhou-kangfu', description: '术后护理、康复指导、功能训练', count: 43 },
];

export const mockProviders = [
  {
    id: 1,
    name: '王阿姨',
    slug: 'wang-ayi-changning',
    providerType: 'individual' as const,
    avgRating: 4.8,
    reviewCount: 47,
    yearsExperience: 10,
    verified: true,
    gender: '女',
    age: 52,
    phone: '138****6789',
    wechatId: 'wang_ayi_care',
    addressText: '上海市长宁区天山街道',
    latitude: 31.216,
    longitude: 121.406,
    bio: '10年居家养老护理经验，曾在三甲医院老年科工作3年。擅长术后康复护理和失能老人日常照护，尤其对髋关节/膝关节术后康复有丰富经验。性格温和有耐心，深受老人和家属信赖。持有高级养老护理员证书和红十字会急救证。',
    district: { name: '长宁区', slug: 'changning-qu' },
    city: { name: '上海市', slug: 'shanghai' },
    listings: [
      { title: '全天居家照护', description: '24小时住家护理，包括饮食起居、服药提醒、康复训练', price: 200, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: false },
      { title: '半天居家照护', description: '8小时日间照护', price: 120, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: false },
      { title: '术后康复护理', description: '针对骨科术后老人的专业康复护理', price: 250, priceUnit: 'day', serviceType: { name: '术后康复', slug: 'shuhou-kangfu' }, isNegotiable: true },
    ],
    verifications: [
      { verifyType: 'id_card', verifyStatus: 'approved' },
      { verifyType: 'nurse_cert', verifyStatus: 'approved' },
      { verifyType: 'health_cert', verifyStatus: 'approved' },
      { verifyType: 'background_check', verifyStatus: 'approved' },
    ],
    photos: [],
    serviceTypes: [
      { serviceType: { name: '居家护理', slug: 'hugong' } },
      { serviceType: { name: '术后康复', slug: 'shuhou-kangfu' } },
    ],
  },
  {
    id: 2,
    name: '李叔叔',
    slug: 'li-shushu-jingan',
    providerType: 'individual' as const,
    avgRating: 4.6,
    reviewCount: 32,
    yearsExperience: 8,
    verified: true,
    gender: '男',
    age: 55,
    phone: '139****8901',
    wechatId: 'li_care_giver',
    addressText: '上海市静安区南京西路街道',
    latitude: 31.228,
    longitude: 121.453,
    bio: '8年养老陪护经验，曾照顾过多位失智老人。擅长阿尔茨海默症老人的日常照护和情绪安抚。有耐心、力气大，可以协助行动不便的老人转移和外出。持有中级养老护理员证书。',
    district: { name: '静安区', slug: 'jingan-qu' },
    city: { name: '上海市', slug: 'shanghai' },
    listings: [
      { title: '全天居家照护', description: '24小时住家护理，特别适合失智老人', price: 220, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: false },
      { title: '陪诊服务', description: '陪同就医、取药、检查', price: 150, priceUnit: 'per_visit', serviceType: { name: '陪诊服务', slug: 'peizhen' }, isNegotiable: false },
      { title: '夜间陪护', description: '夜间8小时陪护，适合需要夜间照看的老人', price: 180, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: true },
    ],
    verifications: [
      { verifyType: 'id_card', verifyStatus: 'approved' },
      { verifyType: 'nurse_cert', verifyStatus: 'approved' },
      { verifyType: 'health_cert', verifyStatus: 'approved' },
    ],
    photos: [],
    serviceTypes: [
      { serviceType: { name: '居家护理', slug: 'hugong' } },
      { serviceType: { name: '陪诊服务', slug: 'peizhen' } },
    ],
  },
  {
    id: 3,
    name: '张阿姨',
    slug: 'zhang-ayi-pudong',
    providerType: 'individual' as const,
    avgRating: 4.9,
    reviewCount: 63,
    yearsExperience: 12,
    verified: true,
    gender: '女',
    age: 48,
    phone: '137****3456',
    wechatId: 'zhang_nurse_pd',
    addressText: '上海市浦东新区陆家嘴街道',
    latitude: 31.235,
    longitude: 121.519,
    bio: '12年专业养老护理经验，原华山医院老年科护士。擅长各类慢性病老人护理，包括高血压、糖尿病、中风后遗症的日常管理。能够进行生命体征监测、胰岛素注射等基础医疗操作。持有护士执业证书和高级养老护理员证书。',
    district: { name: '浦东新区', slug: 'pudong-xinqu' },
    city: { name: '上海市', slug: 'shanghai' },
    listings: [
      { title: '全天居家照护', description: '含基础医疗护理的24小时住家服务', price: 280, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: false },
      { title: '陪诊服务', description: '专业护士陪诊，懂医学术语，能与医生有效沟通', price: 200, priceUnit: 'per_visit', serviceType: { name: '陪诊服务', slug: 'peizhen' }, isNegotiable: false },
      { title: '术后康复', description: '专业术后护理和康复指导', price: 300, priceUnit: 'day', serviceType: { name: '术后康复', slug: 'shuhou-kangfu' }, isNegotiable: true },
      { title: '日间照料', description: '8小时日间照护，含康复训练', price: 180, priceUnit: 'day', serviceType: { name: '日间照料', slug: 'rijian-zhaoliao' }, isNegotiable: false },
    ],
    verifications: [
      { verifyType: 'id_card', verifyStatus: 'approved' },
      { verifyType: 'nurse_cert', verifyStatus: 'approved' },
      { verifyType: 'health_cert', verifyStatus: 'approved' },
      { verifyType: 'background_check', verifyStatus: 'approved' },
    ],
    photos: [],
    serviceTypes: [
      { serviceType: { name: '居家护理', slug: 'hugong' } },
      { serviceType: { name: '陪诊服务', slug: 'peizhen' } },
      { serviceType: { name: '术后康复', slug: 'shuhou-kangfu' } },
      { serviceType: { name: '日间照料', slug: 'rijian-zhaoliao' } },
    ],
  },
  {
    id: 4,
    name: '安康护理站',
    slug: 'ankang-huli-pudong',
    providerType: 'agency' as const,
    avgRating: 4.7,
    reviewCount: 128,
    yearsExperience: null,
    verified: true,
    phone: '021-5****888',
    wechatId: 'ankang_care_center',
    addressText: '上海市浦东新区花木街道',
    latitude: 31.211,
    longitude: 121.548,
    bio: '安康护理站是经上海市卫健委批准设立的专业社区护理机构，拥有20余名持证护工和护士。提供从日常照护到专业医疗护理的全方位服务。所有护工均经过背景调查和严格培训，服务质量由机构统一保障。',
    district: { name: '浦东新区', slug: 'pudong-xinqu' },
    city: { name: '上海市', slug: 'shanghai' },
    listings: [
      { title: '居家护理（标准）', description: '持证护工上门，日常照护服务', price: 180, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: false },
      { title: '居家护理（医疗级）', description: '护士上门，含基础医疗操作', price: 350, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: false },
      { title: '陪诊服务', description: '专人陪诊，含接送和全程陪伴', price: 200, priceUnit: 'per_visit', serviceType: { name: '陪诊服务', slug: 'peizhen' }, isNegotiable: false },
      { title: '日间照料', description: '机构内日托，含午餐和活动', price: 100, priceUnit: 'day', serviceType: { name: '日间照料', slug: 'rijian-zhaoliao' }, isNegotiable: false },
    ],
    verifications: [
      { verifyType: 'id_card', verifyStatus: 'approved' },
      { verifyType: 'nurse_cert', verifyStatus: 'approved' },
    ],
    photos: [],
    serviceTypes: [
      { serviceType: { name: '居家护理', slug: 'hugong' } },
      { serviceType: { name: '陪诊服务', slug: 'peizhen' } },
      { serviceType: { name: '日间照料', slug: 'rijian-zhaoliao' } },
    ],
  },
  {
    id: 5,
    name: '赵阿姨',
    slug: 'zhao-ayi-xuhui',
    providerType: 'individual' as const,
    avgRating: 4.5,
    reviewCount: 19,
    yearsExperience: 6,
    verified: true,
    gender: '女',
    age: 50,
    phone: '136****7890',
    wechatId: 'zhao_care_xh',
    addressText: '上海市徐汇区田林街道',
    latitude: 31.168,
    longitude: 121.43,
    bio: '6年居家养老服务经验，性格开朗，擅长与老人沟通。主要为生活半自理老人提供日间照护，包括做饭、打扫、陪伴聊天、陪同散步等。价格实惠，适合需要日常陪伴的老人。',
    district: { name: '徐汇区', slug: 'xuhui-qu' },
    city: { name: '上海市', slug: 'shanghai' },
    listings: [
      { title: '半天居家照护', description: '4小时日间照护，含做饭和打扫', price: 80, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: false },
      { title: '全天居家照护', description: '8小时日间照护', price: 150, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: true },
    ],
    verifications: [
      { verifyType: 'id_card', verifyStatus: 'approved' },
      { verifyType: 'nurse_cert', verifyStatus: 'approved' },
    ],
    photos: [],
    serviceTypes: [
      { serviceType: { name: '居家护理', slug: 'hugong' } },
    ],
  },
  {
    id: 6,
    name: '颐养天年护理中心',
    slug: 'yiyang-tiannian-hongkou',
    providerType: 'agency' as const,
    avgRating: 4.4,
    reviewCount: 56,
    yearsExperience: null,
    verified: true,
    phone: '021-3****666',
    wechatId: 'yiyang_hongkou',
    addressText: '上海市虹口区四川北路街道',
    latitude: 31.262,
    longitude: 121.484,
    bio: '颐养天年护理中心是虹口区口碑较好的养老服务机构，提供居家护理和日间照料双重服务。团队成员均持证上岗，定期接受专业培训。特别擅长中风后遗症康复护理。',
    district: { name: '虹口区', slug: 'hongkou-qu' },
    city: { name: '上海市', slug: 'shanghai' },
    listings: [
      { title: '居家护理', description: '24小时住家或日间照护', price: 200, priceUnit: 'day', serviceType: { name: '居家护理', slug: 'hugong' }, isNegotiable: false },
      { title: '日间照料', description: '机构内日托，含康复训练', price: 120, priceUnit: 'day', serviceType: { name: '日间照料', slug: 'rijian-zhaoliao' }, isNegotiable: false },
      { title: '中风康复', description: '专业中风后遗症康复护理', price: 250, priceUnit: 'day', serviceType: { name: '术后康复', slug: 'shuhou-kangfu' }, isNegotiable: true },
    ],
    verifications: [
      { verifyType: 'nurse_cert', verifyStatus: 'approved' },
    ],
    photos: [],
    serviceTypes: [
      { serviceType: { name: '居家护理', slug: 'hugong' } },
      { serviceType: { name: '日间照料', slug: 'rijian-zhaoliao' } },
      { serviceType: { name: '术后康复', slug: 'shuhou-kangfu' } },
    ],
  },
];

export const mockReviews = [
  {
    id: 1,
    rating: 5,
    content: '王阿姨照顾我爸三年了，非常细心负责。我爸是髋关节手术后需要康复护理，王阿姨每天按时帮他做康复训练，现在恢复得很好。为人也很真诚，把我们当自己家人一样。强烈推荐！',
    tags: ['细心负责', '专业', '耐心'],
    isVerifiedBooking: true,
    createdAt: '2026-04-15T10:30:00Z',
    user: { nickname: '张先生', avatarUrl: null },
  },
  {
    id: 2,
    rating: 5,
    content: '找到王阿姨是我们的幸运。我妈有轻度认知障碍，有时候会闹脾气，王阿姨特别有办法安抚她。而且王阿姨做饭很好吃，我妈现在胃口好多了。',
    tags: ['态度好', '有经验', '会做饭'],
    isVerifiedBooking: true,
    createdAt: '2026-03-20T14:00:00Z',
    user: { nickname: '李女士', avatarUrl: null },
  },
  {
    id: 3,
    rating: 4,
    content: '王阿姨整体不错，专业能力没得说。唯一小遗憾是有时候会请假，临时找人替班不太方便。但总的来说瑕不掩瑜，还是推荐的。',
    tags: ['专业', '可靠'],
    isVerifiedBooking: true,
    createdAt: '2026-02-10T09:00:00Z',
    user: { nickname: '赵先生', avatarUrl: null },
  },
  {
    id: 4,
    rating: 5,
    content: '非常满意！王阿姨照顾我爷爷走完最后一程，让我们做子女的在工作的时候能安心。最后那段日子她几乎是24小时陪护，从不抱怨。这份恩情我们家一直记着。',
    tags: ['有爱心', '专业', '24小时尽心'],
    isVerifiedBooking: true,
    createdAt: '2025-12-05T16:00:00Z',
    user: { nickname: '陈女士', avatarUrl: null },
  },
];
